name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        include:
          - ruby: '3.2.0'
            bundler: latest
            rubygems: latest

          - ruby: '3.1.4'
            bundler: latest
            rubygems: latest

          - ruby: '3.0'
            bundler: latest
            rubygems: latest

          - ruby: '2.7'
            bundler: '2.4.22'
            rubygems: '3.2.3'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        rubygems: ${{ matrix.rubygems }}
        bundler: ${{ matrix.bundler }}
        # When the following is true, also run "bundle install",
        # and cache the result automatically. Ran into an issue
        # with the caching and multiple ruby version? See commit
        # message for this change.
        bundler-cache: false

    - name: Run the default task
      run: bundle exec rake
